// <auto-generated />
using System;
using System.Collections.Generic;
using Knitnet.CompanyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Knitnet.CompanyApi.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    partial class CompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Knitnet.Shared.Models.AiInterviewMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiInterviewCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_interview_code");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer")
                        .HasColumnName("test_mapping_id");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("ai_interview_mappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AiInterviewResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_code");

                    b.Property<List<string>>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<int>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<List<string>>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.Property<double>("ModuleScoreSecured")
                        .HasColumnType("double precision")
                        .HasColumnName("module_score_secured");

                    b.Property<double>("ModuleTotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("module_total_score");

                    b.Property<List<string>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<int>("ResultBaseId")
                        .HasColumnType("integer")
                        .HasColumnName("result_base_id");

                    b.Property<int>("Wrong")
                        .HasColumnType("integer")
                        .HasColumnName("wrong");

                    b.HasKey("Id");

                    b.HasIndex("ResultBaseId")
                        .IsUnique();

                    b.ToTable("ai_interview_results");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AptitudeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AptitudeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aptitude_code");

                    b.Property<int>("NoOfQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("no_of_questions");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer")
                        .HasColumnName("test_mapping_id");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topics");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("aptitude_mappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AptitudeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AptitudeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aptitude_code");

                    b.Property<int>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<List<string>>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.Property<int>("Incorrect")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect");

                    b.Property<double>("ModuleScoreSecured")
                        .HasColumnType("double precision")
                        .HasColumnName("module_score_secured");

                    b.Property<double>("ModuleTotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("module_total_score");

                    b.Property<List<string>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<int>("ResultBaseId")
                        .HasColumnType("integer")
                        .HasColumnName("result_base_id");

                    b.Property<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("topics");

                    b.Property<List<string>>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("user_answers");

                    b.HasKey("Id");

                    b.HasIndex("ResultBaseId")
                        .IsUnique();

                    b.ToTable("aptitude_results");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CodingMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProblemCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_codes");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer")
                        .HasColumnName("test_mapping_id");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("coding_mappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CodingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<string>("CodingCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coding_code");

                    b.Property<double>("ModuleScoreSecured")
                        .HasColumnType("double precision")
                        .HasColumnName("module_score_secured");

                    b.Property<double>("ModuleTotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("module_total_score");

                    b.Property<int>("ResultBaseId")
                        .HasColumnType("integer")
                        .HasColumnName("result_base_id");

                    b.Property<List<int>>("TestcasePassed")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("testcase_passed");

                    b.Property<List<int>>("TestcaseTotals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("testcase_totals");

                    b.HasKey("Id");

                    b.HasIndex("ResultBaseId")
                        .IsUnique();

                    b.ToTable("coding_results");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.Company", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Uid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CompanyInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanySize")
                        .HasColumnType("text")
                        .HasColumnName("company_size");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer")
                        .HasColumnName("founded_year");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_url");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("company_infos");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CreditPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .IsUnique();

                    b.ToTable("credit_points");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.HR", b =>
                {
                    b.Property<Guid>("HrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hr_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("HrId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("hrs");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.IdentityVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarLast4")
                        .HasColumnType("text")
                        .HasColumnName("aadhaar_last4");

                    b.Property<string>("AadhaarZipUrl")
                        .HasColumnType("text")
                        .HasColumnName("aadhaar_zip_url");

                    b.Property<string>("PassportPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("passport_photo_url");

                    b.Property<string>("ShareCode")
                        .HasColumnType("text")
                        .HasColumnName("share_code");

                    b.Property<string>("UniqueId")
                        .HasColumnType("text")
                        .HasColumnName("unique_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_verifications");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.ResultBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HrId")
                        .HasColumnType("uuid")
                        .HasColumnName("hr_id");

                    b.Property<double>("ScoreSecured")
                        .HasColumnType("double precision")
                        .HasColumnName("score_secured");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_code");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_id");

                    b.Property<int?>("TestMappingId")
                        .HasColumnType("integer")
                        .HasColumnName("test_mapping_id");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId");

                    b.ToTable("results");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestInfo", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("text")
                        .HasColumnName("test_id");

                    b.Property<int>("ApproxStudentCount")
                        .HasColumnType("integer")
                        .HasColumnName("approx_student_count");

                    b.Property<bool>("AptitudeModule")
                        .HasColumnType("boolean")
                        .HasColumnName("aptitude_module");

                    b.Property<bool>("CodingModule")
                        .HasColumnType("boolean")
                        .HasColumnName("coding_module");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<Guid>("HrId")
                        .HasColumnType("uuid")
                        .HasColumnName("hr_id");

                    b.Property<bool>("InterviewModule")
                        .HasColumnType("boolean")
                        .HasColumnName("interview_module");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_code");

                    b.Property<bool>("VerbalModule")
                        .HasColumnType("boolean")
                        .HasColumnName("verbal_module");

                    b.HasKey("TestId");

                    b.HasIndex("CompanyId");

                    b.ToTable("test_infos");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("HrId")
                        .HasColumnType("uuid")
                        .HasColumnName("hr_id");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_code");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("test_mappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("college");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.VerbalMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer")
                        .HasColumnName("test_mapping_id");

                    b.Property<string>("VerbalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verbal_code");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("verbal_mappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.VerbalResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Listening")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("listening");

                    b.Property<Dictionary<string, double>>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<double>("ModuleScoreSecured")
                        .HasColumnType("double precision")
                        .HasColumnName("module_score_secured");

                    b.Property<double>("ModuleTotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("module_total_score");

                    b.Property<int>("ResultBaseId")
                        .HasColumnType("integer")
                        .HasColumnName("result_base_id");

                    b.Property<List<string>>("Speaking")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("speaking");

                    b.Property<string>("VerbalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verbal_code");

                    b.HasKey("Id");

                    b.HasIndex("ResultBaseId")
                        .IsUnique();

                    b.ToTable("verbal_results");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AiInterviewMapping", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestMapping", "TestMapping")
                        .WithOne("AiInterview")
                        .HasForeignKey("Knitnet.Shared.Models.AiInterviewMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AiInterviewResult", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.ResultBase", "ResultBase")
                        .WithOne("AiInterview")
                        .HasForeignKey("Knitnet.Shared.Models.AiInterviewResult", "ResultBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultBase");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AptitudeMapping", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestMapping", "TestMapping")
                        .WithOne("Aptitude")
                        .HasForeignKey("Knitnet.Shared.Models.AptitudeMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.AptitudeResult", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.ResultBase", "ResultBase")
                        .WithOne("Aptitude")
                        .HasForeignKey("Knitnet.Shared.Models.AptitudeResult", "ResultBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultBase");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CodingMapping", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestMapping", "TestMapping")
                        .WithOne("Coding")
                        .HasForeignKey("Knitnet.Shared.Models.CodingMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CodingResult", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.ResultBase", "ResultBase")
                        .WithOne("Coding")
                        .HasForeignKey("Knitnet.Shared.Models.CodingResult", "ResultBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultBase");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.Company", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("Knitnet.Shared.Models.Company", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.CompanyInfo", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.Company", null)
                        .WithOne("CompanyInfo")
                        .HasForeignKey("Knitnet.Shared.Models.CompanyInfo", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knitnet.Shared.Models.HR", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.Company", "Company")
                        .WithMany("HRs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.IdentityVerification", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.User", "User")
                        .WithMany("IdentityVerifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.ResultBase", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestMapping", "TestMapping")
                        .WithMany("Results")
                        .HasForeignKey("TestMappingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestInfo", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.Company", "Company")
                        .WithMany("TestInfos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestMapping", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestInfo", "TestInfo")
                        .WithMany("TestMappings")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestInfo");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.UserProfile", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Knitnet.Shared.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.VerbalMapping", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.TestMapping", "TestMapping")
                        .WithOne("Verbal")
                        .HasForeignKey("Knitnet.Shared.Models.VerbalMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.VerbalResult", b =>
                {
                    b.HasOne("Knitnet.Shared.Models.ResultBase", "ResultBase")
                        .WithOne("Verbal")
                        .HasForeignKey("Knitnet.Shared.Models.VerbalResult", "ResultBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultBase");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.Company", b =>
                {
                    b.Navigation("CompanyInfo");

                    b.Navigation("HRs");

                    b.Navigation("TestInfos");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.ResultBase", b =>
                {
                    b.Navigation("AiInterview");

                    b.Navigation("Aptitude");

                    b.Navigation("Coding");

                    b.Navigation("Verbal");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestInfo", b =>
                {
                    b.Navigation("TestMappings");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.TestMapping", b =>
                {
                    b.Navigation("AiInterview");

                    b.Navigation("Aptitude");

                    b.Navigation("Coding");

                    b.Navigation("Results");

                    b.Navigation("Verbal");
                });

            modelBuilder.Entity("Knitnet.Shared.Models.User", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("IdentityVerifications");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
