// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mapping_api.Data;

#nullable disable

namespace mapping_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mapping_api.Models.AiInterviewMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiInterviewCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("AiInterviewMappings");
                });

            modelBuilder.Entity("mapping_api.Models.AptitudeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AptitudeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoOfQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("AptitudeMappings");
                });

            modelBuilder.Entity("mapping_api.Models.CodingMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProblemCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("CodingMappings");
                });

            modelBuilder.Entity("mapping_api.Models.TestMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HrId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestMappings");
                });

            modelBuilder.Entity("mapping_api.Models.VerbalMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TestMappingId")
                        .HasColumnType("integer");

                    b.Property<string>("VerbalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TestMappingId")
                        .IsUnique();

                    b.ToTable("VerbalMappings");
                });

            modelBuilder.Entity("mapping_api.Models.AiInterviewMapping", b =>
                {
                    b.HasOne("mapping_api.Models.TestMapping", "TestMapping")
                        .WithOne("AiInterview")
                        .HasForeignKey("mapping_api.Models.AiInterviewMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("mapping_api.Models.AptitudeMapping", b =>
                {
                    b.HasOne("mapping_api.Models.TestMapping", "TestMapping")
                        .WithOne("Aptitude")
                        .HasForeignKey("mapping_api.Models.AptitudeMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("mapping_api.Models.CodingMapping", b =>
                {
                    b.HasOne("mapping_api.Models.TestMapping", "TestMapping")
                        .WithOne("Coding")
                        .HasForeignKey("mapping_api.Models.CodingMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("mapping_api.Models.VerbalMapping", b =>
                {
                    b.HasOne("mapping_api.Models.TestMapping", "TestMapping")
                        .WithOne("Verbal")
                        .HasForeignKey("mapping_api.Models.VerbalMapping", "TestMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMapping");
                });

            modelBuilder.Entity("mapping_api.Models.TestMapping", b =>
                {
                    b.Navigation("AiInterview");

                    b.Navigation("Aptitude");

                    b.Navigation("Coding");

                    b.Navigation("Verbal");
                });
#pragma warning restore 612, 618
        }
    }
}
