// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using test_info_api.Data;

#nullable disable

namespace test_info_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417061653_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("test_info_api.Models.TestInfo", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("text");

                    b.Property<int>("ApproxStudentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AptitudeModule")
                        .HasColumnType("boolean");

                    b.Property<bool>("CodingModule")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("HrId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InterviewModule")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VerbalModule")
                        .HasColumnType("boolean");

                    b.HasKey("TestId");

                    b.ToTable("TestInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
